theme: jekyll-theme-hacker
google_analytics: UA-100791701-1
plugins:
  - jemoji
collections:
    cheat_sheets:
        output: true
    tips:
        output: true
    ctf:
        output: true

tips-categories: [Security, Internals, Howto, UX]
